version: '3.8'

volumes:
  pgdata:
    driver: local

services:

  app:
    build: .
    command: sh -c "alembic upgrade head && uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000"
    env_file:
      - ./.env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
#    expose:
#      - 8000
    depends_on:
      - db

  db:
    image: postgres:15.6
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=api_db
    volumes:
      - pgdata:/var/lib/postgresql/data
