from datetime import datetime

# Update time - 20.02.2024
timestamp = 1708461184
last_update_time = datetime.utcfromtimestamp(timestamp)
initial_currencies = [{'name': 'United Arab Emirates Dirham', 'code': 'AED', 'rate': 3.970735},
                      {'name': 'Afghan Afghani', 'code': 'AFN', 'rate': 78.378046},
                      {'name': 'Albanian Lek', 'code': 'ALL', 'rate': 104.053025},
                      {'name': 'Armenian Dram', 'code': 'AMD', 'rate': 438.91978},
                      {'name': 'Netherlands Antillean Guilder', 'code': 'ANG', 'rate': 1.948507},
                      {'name': 'Angolan Kwanza', 'code': 'AOA', 'rate': 898.920094},
                      {'name': 'Argentine Peso', 'code': 'ARS', 'rate': 905.155358},
                      {'name': 'Australian Dollar', 'code': 'AUD', 'rate': 1.64958},
                      {'name': 'Aruban Florin', 'code': 'AWG', 'rate': 1.948638},
                      {'name': 'Azerbaijani Manat', 'code': 'AZN', 'rate': 1.84159},
                      {'name': 'Bosnia-Herzegovina Convertible Mark', 'code': 'BAM', 'rate': 1.9582},
                      {'name': 'Barbadian Dollar', 'code': 'BBD', 'rate': 2.182976},
                      {'name': 'Bangladeshi Taka', 'code': 'BDT', 'rate': 118.665466},
                      {'name': 'Bulgarian Lev', 'code': 'BGN', 'rate': 1.95556},
                      {'name': 'Bahraini Dinar', 'code': 'BHD', 'rate': 0.407438},
                      {'name': 'Burundian Franc', 'code': 'BIF', 'rate': 3097.280555},
                      {'name': 'Bermudan Dollar', 'code': 'BMD', 'rate': 1.081075},
                      {'name': 'Brunei Dollar', 'code': 'BND', 'rate': 1.454283},
                      {'name': 'Bolivian Boliviano', 'code': 'BOB', 'rate': 7.470847},
                      {'name': 'Brazilian Real', 'code': 'BRL', 'rate': 5.330028},
                      {'name': 'Bahamian Dollar', 'code': 'BSD', 'rate': 1.081225},
                      {'name': 'Bitcoin', 'code': 'BTC', 'rate': 2.0729395e-05},
                      {'name': 'Bhutanese Ngultrum', 'code': 'BTN', 'rate': 89.66228},
                      {'name': 'Botswanan Pula', 'code': 'BWP', 'rate': 14.821169},
                      {'name': 'New Belarusian Ruble', 'code': 'BYN', 'rate': 3.538237},
                      {'name': 'Belarusian Ruble', 'code': 'BYR', 'rate': 21189.074654},
                      {'name': 'Belize Dollar', 'code': 'BZD', 'rate': 2.179281},
                      {'name': 'Canadian Dollar', 'code': 'CAD', 'rate': 1.461976},
                      {'name': 'Congolese Franc', 'code': 'CDF', 'rate': 2999.983449},
                      {'name': 'Swiss Franc', 'code': 'CHF', 'rate': 0.952881},
                      {'name': 'Chilean Unit of Account (UF)', 'code': 'CLF', 'rate': 0.037714},
                      {'name': 'Chilean Peso', 'code': 'CLP', 'rate': 1040.643882},
                      {'name': 'Chinese Yuan', 'code': 'CNY', 'rate': 7.774446},
                      {'name': 'Colombian Peso', 'code': 'COP', 'rate': 4236.79872},
                      {'name': 'Costa Rican Colón', 'code': 'CRC', 'rate': 555.95838},
                      {'name': 'Cuban Convertible Peso', 'code': 'CUC', 'rate': 1.081075},
                      {'name': 'Cuban Peso', 'code': 'CUP', 'rate': 28.648494},
                      {'name': 'Cape Verdean Escudo', 'code': 'CVE', 'rate': 110.675107},
                      {'name': 'Czech Republic Koruna', 'code': 'CZK', 'rate': 25.378135},
                      {'name': 'Djiboutian Franc', 'code': 'DJF', 'rate': 192.12866},
                      {'name': 'Danish Krone', 'code': 'DKK', 'rate': 7.454971},
                      {'name': 'Dominican Peso', 'code': 'DOP', 'rate': 63.346539},
                      {'name': 'Algerian Dinar', 'code': 'DZD', 'rate': 145.465166},
                      {'name': 'Egyptian Pound', 'code': 'EGP', 'rate': 33.440903},
                      {'name': 'Eritrean Nakfa', 'code': 'ERN', 'rate': 16.216129},
                      {'name': 'Ethiopian Birr', 'code': 'ETB', 'rate': 61.221206},
                      {'name': 'Euro', 'code': 'EUR', 'rate': 1},
                      {'name': 'Fijian Dollar', 'code': 'FJD', 'rate': 2.443513},
                      {'name': 'Falkland Islands Pound', 'code': 'FKP', 'rate': 0.859062},
                      {'name': 'British Pound Sterling', 'code': 'GBP', 'rate': 0.856406},
                      {'name': 'Georgian Lari', 'code': 'GEL', 'rate': 2.848674},
                      {'name': 'Guernsey Pound', 'code': 'GGP', 'rate': 0.859062},
                      {'name': 'Ghanaian Cedi', 'code': 'GHS', 'rate': 13.480674},
                      {'name': 'Gibraltar Pound', 'code': 'GIP', 'rate': 0.859062},
                      {'name': 'Gambian Dalasi', 'code': 'GMD', 'rate': 73.189464},
                      {'name': 'Guinean Franc', 'code': 'GNF', 'rate': 9310.759976},
                      {'name': 'Guatemalan Quetzal', 'code': 'GTQ', 'rate': 8.432987},
                      {'name': 'Guyanaese Dollar', 'code': 'GYD', 'rate': 226.187858},
                      {'name': 'Hong Kong Dollar', 'code': 'HKD', 'rate': 8.454543},
                      {'name': 'Honduran Lempira', 'code': 'HNL', 'rate': 26.735178},
                      {'name': 'Croatian Kuna', 'code': 'HRK', 'rate': 7.600062},
                      {'name': 'Haitian Gourde', 'code': 'HTG', 'rate': 142.965254},
                      {'name': 'Hungarian Forint', 'code': 'HUF', 'rate': 387.766527},
                      {'name': 'Indonesian Rupiah', 'code': 'IDR', 'rate': 16925.313917},
                      {'name': 'Israeli New Sheqel', 'code': 'ILS', 'rate': 3.970684},
                      {'name': 'Manx pound', 'code': 'IMP', 'rate': 0.859062},
                      {'name': 'Indian Rupee', 'code': 'INR', 'rate': 89.593408},
                      {'name': 'Iraqi Dinar', 'code': 'IQD', 'rate': 1416.208561},
                      {'name': 'Iranian Rial', 'code': 'IRR', 'rate': 45445.699525},
                      {'name': 'Icelandic Króna', 'code': 'ISK', 'rate': 148.49615},
                      {'name': 'Jersey Pound', 'code': 'JEP', 'rate': 0.859062},
                      {'name': 'Jamaican Dollar', 'code': 'JMD', 'rate': 169.357607},
                      {'name': 'Jordanian Dinar', 'code': 'JOD', 'rate': 0.766593},
                      {'name': 'Japanese Yen', 'code': 'JPY', 'rate': 162.16723},
                      {'name': 'Kenyan Shilling', 'code': 'KES', 'rate': 157.837026},
                      {'name': 'Kyrgystani Som', 'code': 'KGS', 'rate': 96.68061},
                      {'name': 'Cambodian Riel', 'code': 'KHR', 'rate': 4411.867518},
                      {'name': 'Comorian Franc', 'code': 'KMF', 'rate': 492.564887},
                      {'name': 'North Korean Won', 'code': 'KPW', 'rate': 972.971303},
                      {'name': 'South Korean Won', 'code': 'KRW', 'rate': 1441.457049},
                      {'name': 'Kuwaiti Dinar', 'code': 'KWD', 'rate': 0.332744},
                      {'name': 'Cayman Islands Dollar', 'code': 'KYD', 'rate': 0.901004},
                      {'name': 'Kazakhstani Tenge', 'code': 'KZT', 'rate': 490.100791},
                      {'name': 'Laotian Kip', 'code': 'LAK', 'rate': 22567.445423},
                      {'name': 'Lebanese Pound', 'code': 'LBP', 'rate': 16250.09808},
                      {'name': 'Sri Lankan Rupee', 'code': 'LKR', 'rate': 337.233398},
                      {'name': 'Liberian Dollar', 'code': 'LRD', 'rate': 206.05409},
                      {'name': 'Lesotho Loti', 'code': 'LSL', 'rate': 20.453683},
                      {'name': 'Lithuanian Litas', 'code': 'LTL', 'rate': 3.192134},
                      {'name': 'Latvian Lats', 'code': 'LVL', 'rate': 0.653932},
                      {'name': 'Libyan Dinar', 'code': 'LYD', 'rate': 5.248659},
                      {'name': 'Moroccan Dirham', 'code': 'MAD', 'rate': 10.878841},
                      {'name': 'Moldovan Leu', 'code': 'MDL', 'rate': 19.36293},
                      {'name': 'Malagasy Ariary', 'code': 'MGA', 'rate': 4905.372234},
                      {'name': 'Macedonian Denar', 'code': 'MKD', 'rate': 61.69563},
                      {'name': 'Myanma Kyat', 'code': 'MMK', 'rate': 2270.483275},
                      {'name': 'Mongolian Tugrik', 'code': 'MNT', 'rate': 3694.350934},
                      {'name': 'Macanese Pataca', 'code': 'MOP', 'rate': 8.708813},
                      {'name': 'Mauritanian Ouguiya', 'code': 'MRU', 'rate': 42.799526},
                      {'name': 'Mauritian Rupee', 'code': 'MUR', 'rate': 49.512454},
                      {'name': 'Maldivian Rufiyaa', 'code': 'MVR', 'rate': 16.646324},
                      {'name': 'Malawian Kwacha', 'code': 'MWK', 'rate': 1818.368344},
                      {'name': 'Mexican Peso', 'code': 'MXN', 'rate': 18.448222},
                      {'name': 'Malaysian Ringgit', 'code': 'MYR', 'rate': 5.167838},
                      {'name': 'Mozambican Metical', 'code': 'MZN', 'rate': 68.625603},
                      {'name': 'Namibian Dollar', 'code': 'NAD', 'rate': 20.410482},
                      {'name': 'Nigerian Naira', 'code': 'NGN', 'rate': 1736.529026},
                      {'name': 'Nicaraguan Córdoba', 'code': 'NIO', 'rate': 39.729773},
                      {'name': 'Norwegian Krone', 'code': 'NOK', 'rate': 11.340604},
                      {'name': 'Nepalese Rupee', 'code': 'NPR', 'rate': 143.459889},
                      {'name': 'New Zealand Dollar', 'code': 'NZD', 'rate': 1.752245},
                      {'name': 'Omani Rial', 'code': 'OMR', 'rate': 0.416097},
                      {'name': 'Panamanian Balboa', 'code': 'PAB', 'rate': 1.08118},
                      {'name': 'Peruvian Nuevo Sol', 'code': 'PEN', 'rate': 4.10635},
                      {'name': 'Papua New Guinean Kina', 'code': 'PGK', 'rate': 4.027062},
                      {'name': 'Philippine Peso', 'code': 'PHP', 'rate': 60.47107},
                      {'name': 'Pakistani Rupee', 'code': 'PKR', 'rate': 302.158404},
                      {'name': 'Polish Zloty', 'code': 'PLN', 'rate': 4.315274},
                      {'name': 'Paraguayan Guarani', 'code': 'PYG', 'rate': 7895.349879},
                      {'name': 'Qatari Rial', 'code': 'QAR', 'rate': 3.936244},
                      {'name': 'Romanian Leu', 'code': 'RON', 'rate': 4.974787},
                      {'name': 'Serbian Dinar', 'code': 'RSD', 'rate': 117.174484},
                      {'name': 'Russian Ruble', 'code': 'RUB', 'rate': 99.994073},
                      {'name': 'Rwandan Franc', 'code': 'RWF', 'rate': 1375.66824},
                      {'name': 'Saudi Riyal', 'code': 'SAR', 'rate': 4.054514},
                      {'name': 'Solomon Islands Dollar', 'code': 'SBD', 'rate': 9.116401},
                      {'name': 'Seychellois Rupee', 'code': 'SCR', 'rate': 14.475794},
                      {'name': 'South Sudanese Pound', 'code': 'SDG', 'rate': 649.725983},
                      {'name': 'Swedish Krona', 'code': 'SEK', 'rate': 11.20634},
                      {'name': 'Singapore Dollar', 'code': 'SGD', 'rate': 1.452609},
                      {'name': 'Saint Helena Pound', 'code': 'SHP', 'rate': 1.361292},
                      {'name': 'Sierra Leonean Leone', 'code': 'SLE', 'rate': 24.479889},
                      {'name': 'Sierra Leonean Leone', 'code': 'SLL', 'rate': 21351.235993},
                      {'name': 'Somali Shilling', 'code': 'SOS', 'rate': 617.830282},
                      {'name': 'Surinamese Dollar', 'code': 'SRD', 'rate': 38.846275},
                      {'name': 'São Tomé and Príncipe Dobra', 'code': 'STD', 'rate': 22376.074733},
                      {'name': 'Salvadoran Colón', 'code': 'SVC', 'rate': 9.460597},
                      {'name': 'Syrian Pound', 'code': 'SYP', 'rate': 14055.905478},
                      {'name': 'Swazi Lilangeni', 'code': 'SZL', 'rate': 20.410988},
                      {'name': 'Thai Baht', 'code': 'THB', 'rate': 38.862503},
                      {'name': 'Tajikistani Somoni', 'code': 'TJS', 'rate': 11.827607},
                      {'name': 'Turkmenistani Manat', 'code': 'TMT', 'rate': 3.783763},
                      {'name': 'Tunisian Dinar', 'code': 'TND', 'rate': 3.392954},
                      {'name': 'Tongan Paʻanga', 'code': 'TOP', 'rate': 2.557121},
                      {'name': 'Turkish Lira', 'code': 'TRY', 'rate': 33.41982},
                      {'name': 'Trinidad and Tobago Dollar', 'code': 'TTD', 'rate': 7.339692},
                      {'name': 'New Taiwan Dollar', 'code': 'TWD', 'rate': 33.994381},
                      {'name': 'Tanzanian Shilling', 'code': 'TZS', 'rate': 2740.526062},
                      {'name': 'Ukrainian Hryvnia', 'code': 'UAH', 'rate': 41.604601},
                      {'name': 'Ugandan Shilling', 'code': 'UGX', 'rate': 4198.146303},
                      {'name': 'United States Dollar', 'code': 'USD', 'rate': 1.081075},
                      {'name': 'Uruguayan Peso', 'code': 'UYU', 'rate': 42.291844},
                      {'name': 'Uzbekistan Som', 'code': 'UZS', 'rate': 13518.845877},
                      {'name': 'Venezuelan Bolívar Fuerte', 'code': 'VEF', 'rate': 3923116.275834},
                      {'name': 'Sovereign Bolivar', 'code': 'VES', 'rate': 39.16561},
                      {'name': 'Vietnamese Dong', 'code': 'VND', 'rate': 26524.18095},
                      {'name': 'Vanuatu Vatu', 'code': 'VUV', 'rate': 130.2308},
                      {'name': 'Samoan Tala', 'code': 'WST', 'rate': 2.972724},
                      {'name': 'CFA Franc BEAC', 'code': 'XAF', 'rate': 656.762093},
                      {'name': 'Silver (troy ounce)', 'code': 'XAG', 'rate': 0.046975},
                      {'name': 'Gold (troy ounce)', 'code': 'XAU', 'rate': 0.000534},
                      {'name': 'East Caribbean Dollar', 'code': 'XCD', 'rate': 2.92166},
                      {'name': 'Special Drawing Rights', 'code': 'XDR', 'rate': 0.8161},
                      {'name': 'CFA Franc BCEAO', 'code': 'XOF', 'rate': 659.455704},
                      {'name': 'CFP Franc', 'code': 'XPF', 'rate': 119.331742},
                      {'name': 'Yemeni Rial', 'code': 'YER', 'rate': 270.647103},
                      {'name': 'South African Rand', 'code': 'ZAR', 'rate': 20.455587},
                      {'name': 'Zambian Kwacha (pre-2013)', 'code': 'ZMK', 'rate': 9730.972087},
                      {'name': 'Zambian Kwacha', 'code': 'ZMW', 'rate': 24.569095},
                      {'name': 'Zimbabwean Dollar', 'code': 'ZWL', 'rate': 348.105785}]
