name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build and start services
      run: docker-compose up -d --build

    - name: Lint with flake8
      run: docker-compose run app flake8 . --exclude=./tests/,./venv/,./.venv/,migrations/ --count --select=E9,F63,F7,F82 --show-source --statistics
        
    - name: Execute tests
      run: docker-compose run app pytest --cov=app --cov-report=term --cov-report=xml

    - name: Codacy Coverage Reporter
      uses: codacy/codacy-coverage-reporter-action@v1.3.0
      with:
        project-token: ${{ secrets.CODACY_CURRENCYAPI_TOKEN }}
        coverage-reports: coverage.xml

    - name: Codacy Code Analysis
      uses: codacy/codacy-analysis-cli-action@v3
      with:
        project-token: ${{ secrets.CODACY_CURRENCYAPI_TOKEN }}
        upload: true

    - name: Shutdown Docker Compose
      run: docker-compose down
